### ISSUE TITLE
 Instructions for updating

### ISSUE THREAD

**Issue by DirectorX** [tkisme/gogs-openshift#5]
Would be nice if there are instructions for updating existing installation

**Comment by tkizm1** [comment]
[easy](https://github.com/tkisme/gogs-openshift/commit/5401b1ec672ac38bd08cf50afb000f7e5fce6a0c)
and update golang is still easy

```
cd $OPENSHIFT_DATA_DIR
rm -rf go
ls
curl https://storage.googleapis.com/golang/go1.6.linux-amd64.tar.gz | tar -xzf - -C $OPENSHIFT_DATA_DIR
gear restart
```

anyway I will update my doc ^_^
